version: '3.7'

volumes:
  postgres_data:
    driver: local

services:
  books_db:
    image: postgres:latest
    container_name: books_db
    volumes:
      - ./etc/db/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: picket
      POSTGRES_PASSWORD: picket
      POSTGRES_DB: books
    ports:
      - "6432:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./etc/keycloak:/opt/keycloak/data/import
    ports:
      - "8080:8080"
